name: "Deploy SAM Stack to Production"
on: 
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install aws-sam-cli
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build and Deploy
        run: sam build && sam deploy
        env:
            TEMPLATE: 'template.yaml'
            AWS_STACK_NAME: sam-app
            AWS_REGION: 'us-east-1'
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_BUCKET_PREFIX: sam-app
            PARAMETER_OVERRIDES: tableName=\"lambda_async_results\""
